// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onhykcqmgyzjthzfujxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uaHlrY3FtZ3l6anRoemZ1anhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MTEwMDYsImV4cCI6MjA3NjI4NzAwNn0.y-GWNDzg3rLkvkIbZGa_xUp98UM8lKetUe5m_AdteHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});